# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

############################
## Theme
############################

# Choose a theme.
#   Latest themes (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in themes in `themes/academic/data/themes/`
#   Browse user installed themes in `data/themes/`
theme = "ocean"
# Enable users to switch between day and night mode?
day_night = false

GoogleAnalyticsApiUrl = "https://api.amrcloud.net/api"

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font = ""
font_size = "L"

############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type = "Project"

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type = ""

# Organization name (optional)
# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name = ""

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "AMRcloud (AntiMicrobial Resistance Cloud) is a web platform for analysis and sharing of AMR surveillance data. "

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = "amr-cloud-logo-text.png"

# Twitter username (without @). Used when a vistor shares your site on Twitter.
twitter = "@iacmac1997"

# Diplay a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

############################
## Site Features
############################

# Enable global source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
# highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = false

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = true

############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "2006-01-02"
#   Examples: "3:04 pm" or "15:04"
time_format = "15:04"
# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"


############################
## Contact Widget setup   ##
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "support@antibiotic.ru"
phone = ""
# address = {street = "", city = "", region = "", postcode = "", country = "", country_code = ""}
# Geographic coordinates
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
# coordinates = {latitude = "37.4275", longitude = "-122.1697"}
# Directions for visitors to locate you.
# directions = "Enter Building 1 and take the stairs to Office 200 on Floor 2"

# office_hours = ["Monday 10:00 to 13:00", "Wednesday 09:00 to 10:00"]
office_hours = ""


# Enter an optional link for booking appointments (e.g. calendly.com).
appointment_url = ""

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links = [
  {icon = "internet-explorer", icon_pack = "fab", name = "AMRhub.ru", link = "http://amrhub.ru/"},
  {icon = "twitter", icon_pack = "fab", name = "twitter.com/iacmac1997", link = "https://twitter.com/iacmac1997"},
  {icon = "instagram", icon_pack = "fab", name = "instagram.com/iacmac1997", link = "https://instagram.com/iacmac1997"},
  {icon = "facebook", icon_pack = "fab", name = "facebook.com/iacmac", link = "https://facebook.com/iacmac"},
  {icon = "vk", icon_pack = "fab", name = "vk.com/iacmac", link = "https://vk.com/iacmac"},
  {icon = "telegram", icon_pack = "fab", name = "telegram.me/iacmac", link = "https://telegram.me/iacmac"},
  ]


############################
## Plugins                ##
############################

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js  = []

############################
## Advanced options       ##
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "l", show_logo = true}

# Show estimated reading time for posts? (true/false)
reading_time = false

# Display comment count (if commenting enabled in config.toml)? (true/false)
comment_count = false

# Display next/previous section pager? (true/false)
section_pager = true
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Link authors to their profile page? (true/false)
link_authors = true

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}


# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

############################
## Search
############################
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false


############################
## Documentation TOC settings
############################
toc_levels = 4

############################
## Maps
############################
# [map]
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  # engine = 0
  # api_key = ""
  # zoom = 15

############################
## Comments
############################
[comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  #   3: Remark42 
  engine = 0

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)
  # Config Remark
  [comments.remark]
    url = ""
    site_id = ""

############################
## Marketing
############################
[marketing]
  google_analytics = "UA-85066436-14"
  google_tag_manager = ""